### ISSUE TITLE
Unable to run pip install -e samr -r samr/docs/setup/requirements-dev.txt

### ISSUE THREAD

**Issue by kevlaria** [rafacarrascosa/samr#2]
Looks like pip.parse_requirements needs a session argument (for pip 6.0+), otherwise it will raise an exception. 

c/f https://github.com/jmcarp/robobrowser/pull/32

**Comment by rafacarrascosa** [comment]
Thanks for reporting! I'm working on it right now

**Comment by rafacarrascosa** [comment]
Solved just now, can you verify @kevlaria ?

**Comment by kevlaria** [comment]
Thanks for the fast reply! - Yes, it works now!

**Comment by kevlaria** [comment]
btw, thanks for sharing this! It's super helpful!

**Comment by rafacarrascosa** [comment]
my pleasure!
