### ISSUE TITLE
how to change fit_ovo to OneVsOneClassifier in sklearn 1.80

### ISSUE THREAD

**Issue by tonywangcn** [rafacarrascosa/samr#3]
change "from sklearn.multiclass fit_ovo" fit_ovo to OneVsOneClassifier, because of fit_ovo is deprecated.

I'm using sklearn 1.80 , is it possible to change the code to make it compatible?

Thanks!

**Comment by rafacarrascosa** [comment]
Fixed in #4 , thanks @tonywangcn !
